spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

server:
  port: 9999

info:
  app:
    name: myApplication
    threadCount: 4
    users:
      - song
      - ning
