spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
# 默认配置
#    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      connection-init-sqls: set names utf8mb4
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      use-global-data-source-stat: true
      filter:
        wall:
          config:
            multi-statement-allow: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
        slf4j:
          enabled: true
          connection-log-enabled: true
          statement-executable-sql-log-enable: true
          result-set-log-enabled: false
      min-evictable-idle-time-millis: 1800000
      stat-view-servlet:
        enabled: true
      rds:
        maxActive: 10
        maxOpenPrepareStatements: 10
      primary-data:
        url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
      ads:
        maxActive: 10
        maxOpenPrepareStatements: 10
      second-data:
        url: jdbc:mysql://localhost:3306/spring_durid?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  redis:
    database: 1   # 数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8    # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8      # 连接池中的最大空闲连接
        min-idle: 0      #连接池中的最小空闲连接
#    timeout: 0           # 连接超时时间（毫秒）

server:
  port: 9999

#测试注入数据
info:
  app:
    name: myApplication
    threadCount: 4
    users:
      - song
      - ning
